name = "IMASutils"
uuid = "b8e4ee59-9bed-3a6a-a553-8dd24d6374ad"
authors = ["Brendan Lyons <lyonsbc@fusion.gat.com> and contributors"]
version = "1.4.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1.9.8"
julia = "1"
